server:
  port: 8181
spring:
  application:
    name: crossplatform-updater
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always 
      data-locations: classpath:sql/data.sql
jwt: 
  secret: ${JWT_SECRET_KEY}
  access:
    duration:
      minutes: 5
      second: 300
    cookie-name: access-token
  refresh:
    duration:
      days: 7
      second: 604800
    cookie-name: refresh-token
